import java.util.*;
import src.*;

/*
    LOAD TEST GENERATED BY CLAUDE FOR CHAINED & OPEN ADDRESSING MAPS.
*/

public class Main {
 
    private static final String GREEN = "\u001B[32m";
    private static final String RED   = "\u001B[31m";
    private static final String BOLD  = "\u001B[1m";
    private static final String RESET = "\u001B[0m";
 
    private static int passed = 0, failed = 0;
 
    public static void main(String[] args) {
        System.out.println(BOLD + "\n── ChainingHashTable ──────────────────────" + RESET);
        runSuite("Chaining", new ChainingHashTable<>());
 
        System.out.println(BOLD + "\n── OpenAddressing (Linear) ────────────────" + RESET);
        runSuite("Linear", new OpenAddressingHashTable<>(new LinearProbe()));
 
        System.out.println(BOLD + "\n── OpenAddressing (Quadratic) ─────────────" + RESET);
        runSuite("Quadratic", new OpenAddressingHashTable<>(new QuadraticProbe()));
 
        System.out.println(BOLD + "\n── OpenAddressing (DoubleHashing) ─────────" + RESET);
        runSuite("DoubleHashing", new OpenAddressingHashTable<>(new DoubleHashingProbe()));
 
        System.out.println(BOLD + "\n══════════════════════════════════════════" + RESET);
        System.out.printf(BOLD + "  %s%d passed%s  %s%d failed%s  (of %d)%n" + RESET,
                GREEN, passed, RESET,
                failed > 0 ? RED : GREEN, failed, RESET,
                passed + failed);
        System.out.println(BOLD + "══════════════════════════════════════════\n" + RESET);
    }
 
    private static void runSuite(String name, IMap<Integer, Integer> map) {
        Random rng = new Random(42L);
        Map<Integer, Integer> ref = new HashMap<>();
 
        // 1. Sequential insert + get
        long t = System.nanoTime();
        for (int i = 0; i < 10_000; i++) { map.put(i, i * 2); ref.put(i, i * 2); }
        boolean r1 = matchesRef(map, ref);
        check(name, "Sequential insert+get", r1, System.nanoTime() - t);
 
        // 2. Update returns old value
        t = System.nanoTime();
        Integer old = map.put(0, 999);
        check(name, "put() returns old value", old != null && old == 0 && map.get(0) == 999, System.nanoTime() - t);
        map.put(0, 0); ref.put(0, 0);
 
        // 3. Delete correctness
        t = System.nanoTime();
        for (int i = 0; i < 5_000; i += 2) { map.delete(i); ref.remove(i); }
        check(name, "Delete correctness", matchesRef(map, ref), System.nanoTime() - t);
 
        // 4. Delete non-existent key
        t = System.nanoTime();
        Integer gone = map.delete(99999);
        check(name, "delete() non-existent returns null", gone == null && map.size() == ref.size(), System.nanoTime() - t);
 
        // 5. Mixed workload vs reference
        t = System.nanoTime();
        for (int i = 0; i < 50_000; i++) {
            int k = rng.nextInt(2_000);
            int op = rng.nextInt(3);
            if (op == 0)      { int v = rng.nextInt(500); map.put(k, v); ref.put(k, v); }
            else if (op == 1) { map.get(k); }
            else              { map.delete(k); ref.remove(k); }
        }
        check(name, "Mixed workload (50k ops)", matchesRef(map, ref), System.nanoTime() - t);
 
        // 6. Clear
        t = System.nanoTime();
        map.clear();
        check(name, "clear() resets size", map.size() == 0 && map.isEmpty(), System.nanoTime() - t);
 
        // 7. Usable after clear
        t = System.nanoTime();
        map.put(1, 1);
        check(name, "Usable after clear", map.size() == 1 && map.get(1) == 1, System.nanoTime() - t);
    }
 
    private static boolean matchesRef(IMap<Integer, Integer> map, Map<Integer, Integer> ref) {
        if (map.size() != ref.size()) return false;
        for (Map.Entry<Integer, Integer> e : ref.entrySet()) {
            if (!Objects.equals(map.get(e.getKey()), e.getValue())) return false;
        }
        return true;
    }
 
    private static void check(String impl, String test, boolean ok, long ns) {
        String time = String.format("%6.2f ms", ns / 1_000_000.0);
        if (ok) { passed++; System.out.printf("  %s✔%s  %-45s %s  (%s)%n", GREEN, RESET, test, time, impl); }
        else    { failed++; System.out.printf("  %s✘%s  %-45s %s  (%s)%n", RED,   RESET, test, time, impl); }
    }
}